teamRed: ["lalmeida", "aabdolmaleki", "nshafii", "mlopes"]
teamGreen: ["pdias", "jalves", "dsilva", "pkumars"]
teamBlue: ["rsalgueiro", "tsimoes", "mkasaei", "torrao"]

#teamRed: ["moliveira"]
#teamGreen: ["lalmeida"]
#teamBlue: ["rsalgueiro", "tsimoes", "mkasaei"]

hunting_distance: 0.5
game_duration: 120
positive_score: 1
negative_score: 0





